### ISSUE TITLE
Error occurs (table not found) if field name has an uppercase letter

### ISSUE THREAD

**Issue by jlahijani** [Toutouwai/ProcessMediaLister#3]
In ProcessWire, assume you have an image field (or any field for that matter) named: `myImages` (capital I)

The table is then called: `field_myimages` (all lowercase)

In this module, when using `$field->name` it will get `myimages` which as a result will cause this line to fail:
https://github.com/Toutouwai/ProcessMediaLister/blob/master/ProcessMediaLister.module#L358

**Comment by Toutouwai** [comment]
Thanks, fixed in v0.1.3
